# Generated by Django 2.2.9 on 2025-02-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeatureconfig',
            name='phone_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
