# Generated by Django 2.2.9 on 2025-02-23 14:04

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherUploadingVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.TextField(blank=True, null=True)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('edubond_report', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('parent_report', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('audio_path', models.TextField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
