# Generated by Django 2.2.9 on 2025-02-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_teacheruploadingvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruploadingvideo',
            name='topic_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
